# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - master

# env:
#   IMAGE_TAG: ${{ github.sha }}

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and Push Backend
#         run: |
#           docker build -t tanvir014/dinewise-backend:latest ./dinewise
#           docker push tanvir014/dinewise-backend:latest

#       - name: Build and Push Frontend
#         run: |
#           docker build -t tanvir014/dinewise-frontend:latest ./frontend
#           docker push tanvir014/dinewise-frontend:latest

#       - name: Deploy to Azure VM via SSH
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd ~/Documents/Project/dinewise
#             docker-compose pull
#             docker-compose down
#             docker-compose up -d


name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t tanvir014/dinewise-backend:${IMAGE_TAG} ./dinewise
          docker tag tanvir014/dinewise-backend:${IMAGE_TAG} tanvir014/dinewise-backend:latest
          docker push tanvir014/dinewise-backend:${IMAGE_TAG}
          docker push tanvir014/dinewise-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t tanvir014/dinewise-frontend:${IMAGE_TAG} ./frontend
          docker tag tanvir014/dinewise-frontend:${IMAGE_TAG} tanvir014/dinewise-frontend:latest
          docker push tanvir014/dinewise-frontend:${IMAGE_TAG}
          docker push tanvir014/dinewise-frontend:latest

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Documents/Project/dinewise
            export IMAGE_TAG=${{ github.sha }}
            git pull

            # Remove old containers & images
            docker-compose down --remove-orphans
            docker image rm tanvir014/dinewise-backend:latest || true
            docker image rm tanvir014/dinewise-frontend:latest || true

            # Pull and start new containers
            docker-compose pull
            docker-compose up --build -d
